/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DTO.DTONhanVien;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Point;
import java.awt.Polygon;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JWindow;

/**
 *
 * @author vudt9
 */
public class Frm_Login extends javax.swing.JFrame {

    public int[] x = {0, 20, 300, 300, 20};
    public int[] y = {20, 0, 0, 40, 40};
    MessagePopup loiSaiMatKhau;
    MessagePopup loiDangNhap;
    public static boolean checkLoadDone = false;
    public static int maNVPhienHienTai = 1;
    private final char[] UallowChars = "abcdefghijklmnopqrstuvwxyz0123456789-_".toCharArray();
    private final char[] PallowChars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789".toCharArray();

    /**
     * Creates new form Frm_Login
     */
    public Frm_Login() {
        initComponents();
        jLabel4.requestFocus();
        loiSaiMatKhau = new MessagePopup(this, "Mật khẩu không đúng");
        loiDangNhap = new MessagePopup(this, "Tên người dùng không tồn tại");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_bg = new javax.swing.JPanel();
        pnl_Loader = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        pnl_Login = new javax.swing.JPanel();
        txt_UserName = new javax.swing.JTextField();
        pwd_Password = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setLocationByPlatform(true);
        setUndecorated(true);

        pnl_bg.setBackground(new java.awt.Color(255, 255, 255));
        pnl_bg.setLayout(new java.awt.CardLayout());

        pnl_Loader.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/loader.gif"))); // NOI18N
        jLabel5.setText("jLabel5");

        javax.swing.GroupLayout pnl_LoaderLayout = new javax.swing.GroupLayout(pnl_Loader);
        pnl_Loader.setLayout(pnl_LoaderLayout);
        pnl_LoaderLayout.setHorizontalGroup(
            pnl_LoaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_LoaderLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(163, Short.MAX_VALUE))
        );
        pnl_LoaderLayout.setVerticalGroup(
            pnl_LoaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_LoaderLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        pnl_bg.add(pnl_Loader, "card3");

        pnl_Login.setBackground(new java.awt.Color(255, 255, 255));
        pnl_Login.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txt_UserName.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        txt_UserName.setToolTipText("");
        txt_UserName.setBorder(null);
        GhostText userName = new GhostText(txt_UserName, "Tên đăng nhập");
        txt_UserName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_UserNameFocusGained(evt);
            }
        });
        txt_UserName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_UserNameKeyTyped(evt);
            }
        });

        pwd_Password.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        pwd_Password.setBorder(null);
        GhostText pwd = new GhostText(pwd_Password, "Mật khẩu");
        pwd_Password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pwd_PasswordFocusGained(evt);
            }
        });
        pwd_Password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pwd_PasswordKeyTyped(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/icons8_Contacts_32px.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/icons8_Padlock_32px.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Đăng nhập");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/icons8_Delete_32px_1.png"))); // NOI18N
        jLabel4.setToolTipText("");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Ghi nhớ tài khoản");

        jButton1.setBackground(new java.awt.Color(0, 76, 64));
        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Đăng nhập");
        jButton1.setContentAreaFilled(false);
        jButton1.setOpaque(true);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_LoginLayout = new javax.swing.GroupLayout(pnl_Login);
        pnl_Login.setLayout(pnl_LoginLayout);
        pnl_LoginLayout.setHorizontalGroup(
            pnl_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(pnl_LoginLayout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addGroup(pnl_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(pnl_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(pnl_LoginLayout.createSequentialGroup()
                            .addComponent(jCheckBox1)
                            .addGap(52, 52, 52)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnl_LoginLayout.createSequentialGroup()
                            .addGroup(pnl_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(pnl_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_UserName, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                                .addComponent(pwd_Password)
                                .addComponent(jSeparator1)
                                .addComponent(jSeparator2)))))
                .addGap(143, 143, 143))
        );
        pnl_LoginLayout.setVerticalGroup(
            pnl_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_LoginLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addGap(48, 48, 48)
                .addGroup(pnl_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_UserName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnl_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pwd_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(pnl_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pnl_bg.add(pnl_Login, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel4MouseClicked

    public void doiThe() {
        CardLayout cl = (CardLayout) (pnl_bg.getLayout());
        cl.show(pnl_bg, "card2");
    }

    private void txt_UserNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_UserNameFocusGained
        loiDangNhap.setVisible(false);
        jSeparator1.setForeground(new Color(160, 160, 160));
    }//GEN-LAST:event_txt_UserNameFocusGained

    private void pwd_PasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwd_PasswordFocusGained
        loiSaiMatKhau.setVisible(false);
        jSeparator2.setForeground(new Color(160, 160, 160));
    }//GEN-LAST:event_pwd_PasswordFocusGained

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String userName = txt_UserName.getText();
        String passWord = new String(pwd_Password.getPassword());
        if (DAL.DALNhanVien.kiemTraUserName(userName) == false) {
            Point location = txt_UserName.getLocationOnScreen();
            loiDangNhap.setLocation(location.x + txt_UserName.getWidth(), location.y);
            loiDangNhap.setVisible(true);
            jSeparator1.setForeground(Color.red);
            return;
        }
        if (DAL.DALNhanVien.kiemTraPassword(userName, passWord) == false) {
            Point location = pwd_Password.getLocationOnScreen();
            loiSaiMatKhau.setLocation(location.x + pwd_Password.getWidth(), location.y);
            loiSaiMatKhau.setVisible(true);
            jSeparator2.setForeground(Color.red);
            return;
        }
        DTONhanVien nv = DAL.DALNhanVien.layThongTinNVDaDN(userName, passWord);
        maNVPhienHienTai = nv.getMaNV();
        Frm_Main.main(nv.getTenNV()); // <- set tên của user hiện tại vào đây
        this.setVisible(false);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        jButton1.setBackground(new Color(0, 121, 107));
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        jButton1.setBackground(new Color(0, 76, 64));
    }//GEN-LAST:event_jButton1MouseExited

    private void txt_UserNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_UserNameKeyTyped
        if (txt_UserName.getText().length() >= 20 || evt.getKeyCode() == KeyEvent.VK_CONTROL) {
            evt.consume();
        }
        int count = 0;
        for (int i = 0; i < UallowChars.length; i++) {
            if (evt.getKeyChar() == UallowChars[i]) {
                count++;
                break;
            }
        }
        if (count == 0) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_UserNameKeyTyped

    private void pwd_PasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwd_PasswordKeyTyped
        if (pwd_Password.getPassword().length >= 20 || evt.getKeyCode() == KeyEvent.VK_CONTROL) {
            evt.consume();
        }
        int count = 0;
        for (int i = 0; i < PallowChars.length; i++) {
            if (evt.getKeyChar() == PallowChars[i]) {
                count++;
                break;
            }
        }
        if (count == 0) {
            evt.consume();
        }
    }//GEN-LAST:event_pwd_PasswordKeyTyped

    class MessagePopup extends JWindow {

        public MessagePopup(javax.swing.JFrame parent, String message) {
            super(parent);
            setShape(new Polygon(x, y, 5));
            setSize(300, 300);
            getContentPane().setBackground(new Color(190, 75, 73));
            JLabel lb = new JLabel(message);
            lb.setForeground(Color.WHITE);
            lb.setFont(new java.awt.Font("Segoe UI", 0, 18));
            getContentPane().setLayout(new java.awt.FlowLayout());
            getContentPane().add(lb);
            setLocationRelativeTo(parent);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel pnl_Loader;
    private javax.swing.JPanel pnl_Login;
    private javax.swing.JPanel pnl_bg;
    private javax.swing.JPasswordField pwd_Password;
    private javax.swing.JTextField txt_UserName;
    // End of variables declaration//GEN-END:variables
}
