/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author vudt9
 */
public class KhuyenMai_Card extends javax.swing.JPanel {
    
    private int maKM;
    
    public int getMaKM() {
        return maKM;
    }
    
    public void setMaKM(int maKM) {
        this.maKM = maKM;
    }

    /**
     * Creates new form KhuyenMai_Card
     */
    public KhuyenMai_Card() {
        initComponents();
    }
    
    public KhuyenMai_Card(int maKM) {
        initComponents();
        this.maKM = maKM;
        loadThongTinKM();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pmn_TuyChon = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        lbl_BeginEnd = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lbl_TenKM = new javax.swing.JLabel();

        pmn_TuyChon.setBackground(new java.awt.Color(255, 255, 255));
        pmn_TuyChon.setBorder(null);
        pmn_TuyChon.setBorderPainted(false);
        pmn_TuyChon.setInvoker(jButton1);
        pmn_TuyChon.setLabel("");

        jMenuItem1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItem1.setText("Chỉnh sửa KM");
        jMenuItem1.setContentAreaFilled(false);
        jMenuItem1.setOpaque(true);
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        pmn_TuyChon.add(jMenuItem1);

        jMenuItem2.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItem2.setText("Dừng chương trình KM");
        jMenuItem2.setContentAreaFilled(false);
        jMenuItem2.setOpaque(true);
        pmn_TuyChon.add(jMenuItem2);

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(0, 121, 107));

        lbl_BeginEnd.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lbl_BeginEnd.setForeground(new java.awt.Color(255, 255, 255));
        lbl_BeginEnd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_BeginEnd.setText("<html>\n<center>\n<font size=\"12\">12 </font>\n<p>Thg Hai 2017</p>\n<p>10:00 SA</p>\n<p></p>\n<center><font size=\"12\">25 </font></center>\n<p>Thg Năm 2017</p>\n<p>23:00 SA</p>\n</center>\n</html>");
        lbl_BeginEnd.setComponentPopupMenu(pmn_TuyChon);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_BeginEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_BeginEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/icons8_Menu_24px.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lbl_TenKM.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lbl_TenKM.setText("<html>\n<p>Chương trình khuyến mãi</p> \n<p>tháng 6 năm 2017</p>\n</html>");
        lbl_TenKM.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_TenKM, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_TenKM, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        pmn_TuyChon.setLocation(jButton1.getLocationOnScreen().x, jButton1.getLocationOnScreen().y + jButton1.getHeight());
        pmn_TuyChon.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void loadThongTinKM() {
        DTO.DTOChuongTrinhKM km = DAL.DALChuongTrinhKM.layDuLieu(maKM);
        lbl_TenKM.setText(km.getTenKM());
        lbl_BeginEnd.setText("<html>\n"
                + "<center>\n"
                + "<font size=\"12\">12 </font>\n"
                + "<p>Thg Hai 2017</p>\n"
                + "<p>10:00 SA</p>\n"
                + "<p></p>\n"
                + "<center><font size=\"12\">25 </font></center>\n"
                + "<p>Thg Năm 2017</p>\n"
                + "<p>23:00 SA</p>\n"
                + "</center>\n"
                + "</html>");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_BeginEnd;
    private javax.swing.JLabel lbl_TenKM;
    private javax.swing.JPopupMenu pmn_TuyChon;
    // End of variables declaration//GEN-END:variables
}
