/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DTO.ConvertDateFormat;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vudt9
 */
public class Pnl_BaoCao extends javax.swing.JPanel {

    /**
     * Creates new form Pnl_BaoCao
     */
    public Pnl_BaoCao() {
        initComponents();
        doDuLieuLenTableBaoCao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_BaoCao = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("BÁO CÁO BÁN HÀNG");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tháng 1", "Tháng 2", "Tháng 3" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Năm 2015", "Năm 2016", "Năm 2017" }));

        tbl_BaoCao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, "Tổng cộng", null, null, null, null, null}
            },
            new String [] {
                "STT", "Tên sản phẩm", "Số lượng bán", "Đơn giá bán", "Tiền bán", "Tiền khuyến mãi", "Doanh thu"
            }
        ));
        tbl_BaoCao.setRowHeight(24);
        jScrollPane1.setViewportView(tbl_BaoCao);

        jButton1.setText("Xuất ra file Excel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 289, Short.MAX_VALUE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 201, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void doDuLieuLenTableBaoCao() {
        Date ngayBatDau = ConvertDateFormat.chuyenNgay("01/11/2017");
        Date ngayKetThuc = ConvertDateFormat.chuyenNgay("01/12/2017");
        DTO.DTOBaoCao[] arrBC = DAL.DALChiTietHoaDon.layBaoCao(ngayBatDau, ngayKetThuc);
        DefaultTableModel model = (DefaultTableModel) tbl_BaoCao.getModel();
        model.setRowCount(0);
        int sumSoLuongBan = 0;
        int sumTienBan = 0;
        int sumDoanhThu = 0;
        for (int i = 0; i < arrBC.length; i++) {
            Object[] obj = new Object[7];
            obj[0] = i + 1;
            obj[1] = arrBC[i].getTenSP();
            obj[2] = arrBC[i].getSoLuongBan();
            sumSoLuongBan = sumSoLuongBan + arrBC[i].getSoLuongBan();
            obj[3] = arrBC[i].getDonGiaBan();
            obj[4] = arrBC[i].getTienBan();
            sumTienBan = sumTienBan + arrBC[i].getTienBan();
            obj[5] = arrBC[i].getTienKM();
            obj[6] = arrBC[i].getDoanhThu();
            sumDoanhThu = sumDoanhThu + arrBC[i].getDoanhThu();
            model.addRow(obj);
        }
        //Last row
        Object[] obj = new Object[7];
        obj[0] = "";
        obj[1] = "<html><h3><b><font color='green'>Tổng cộng</font></b></h3></html>";
        obj[2] = "<html><h3><b><font color='blue'>"+sumSoLuongBan+"</font></b></h3></html>";
        obj[3] = "";
        obj[4] = "<html><h3><b><font color='blue'>"+sumTienBan+"</font></b></h3></html>";
        obj[5] = "";
        obj[6] = "<html><h3><b><font color='blue'>"+sumDoanhThu+"</font></b></h3></html>";
        model.addRow(obj);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_BaoCao;
    // End of variables declaration//GEN-END:variables
}
