/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAL.DALKhachHang;
import DAL.DALSanPham;
import DTO.DTOKhachHang;
import DTO.DTOSanPham;
import DTO.ThongBao;
import java.awt.Frame;
import java.awt.event.ActionEvent;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vudt9
 */
public class Pnl_TaoHoaDon extends javax.swing.JPanel {

    /**
     * Creates new form pnlTaoHoaDon
     */
    public Pnl_TaoHoaDon() {
        initComponents();
        XuLyCbb.capNhatCbb(cbbNhanVien, DAL.DALNhanVien.layDuLieu());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popMenuTimKiem = new javax.swing.JPopupMenu();
        popMenuTKKH = new javax.swing.JPopupMenu();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGioHang = new javax.swing.JTable();
        PnlTongTienHD = new javax.swing.JPanel();
        LblTongTien = new javax.swing.JLabel();
        txtTongTien = new javax.swing.JTextField();
        LblTienKhachTra = new javax.swing.JLabel();
        txtTienKhachTra = new javax.swing.JTextField();
        LblTienDu = new javax.swing.JLabel();
        txtTienDu = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtKhungTimKiem = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbbNhanVien = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        txtGhiChu = new javax.swing.JTextField();
        jdcNgayTaoHD = new com.toedter.calendar.JDateChooser();
        jPanel11 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtKhungTKKH = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtTenKH = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtSoDT = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        txtGhiChuKH = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cbbGioiTinh = new javax.swing.JComboBox<>();
        datNgaySinh = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        txtMaKH = new javax.swing.JTextField();
        chbTaoKHMoi = new javax.swing.JCheckBox();
        btnThanhToan = new javax.swing.JButton();
        btnTaoHDMoi = new javax.swing.JButton();

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Giỏ hàng"));

        tblGioHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã SP", "Tên SP", "Số lượng", "Đơn vị tính", "Giá", "Thành tiền"
            }
        ));
        jScrollPane1.setViewportView(tblGioHang);

        PnlTongTienHD.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        LblTongTien.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LblTongTien.setText("Tổng Tiền");

        txtTongTien.setEditable(false);
        txtTongTien.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtTongTien.setForeground(new java.awt.Color(0, 0, 255));
        txtTongTien.setText("0");
        txtTongTien.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTongTienFocusGained(evt);
            }
        });

        LblTienKhachTra.setText("Tiền Khách Trả");

        txtTienKhachTra.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtTienKhachTra.setForeground(new java.awt.Color(0, 0, 255));
        txtTienKhachTra.setText("0");
        txtTienKhachTra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTienKhachTraKeyReleased(evt);
            }
        });

        LblTienDu.setText("Tiền Dư");

        txtTienDu.setEditable(false);
        txtTienDu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtTienDu.setForeground(new java.awt.Color(0, 0, 255));
        txtTienDu.setText("0");

        javax.swing.GroupLayout PnlTongTienHDLayout = new javax.swing.GroupLayout(PnlTongTienHD);
        PnlTongTienHD.setLayout(PnlTongTienHDLayout);
        PnlTongTienHDLayout.setHorizontalGroup(
            PnlTongTienHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlTongTienHDLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnlTongTienHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblTongTien)
                    .addComponent(LblTienKhachTra)
                    .addComponent(LblTienDu))
                .addGap(47, 47, 47)
                .addGroup(PnlTongTienHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTongTien, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(txtTienKhachTra)
                    .addComponent(txtTienDu))
                .addContainerGap())
        );
        PnlTongTienHDLayout.setVerticalGroup(
            PnlTongTienHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlTongTienHDLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnlTongTienHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblTongTien)
                    .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PnlTongTienHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblTienKhachTra)
                    .addComponent(txtTienKhachTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PnlTongTienHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTienDu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblTienDu))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PnlTongTienHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PnlTongTienHD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("Tên/Mã sản phẩm:");

        txtKhungTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtKhungTimKiemKeyReleased(evt);
            }
        });

        jButton2.setText("Tìm kiếm");
        jButton2.setToolTipText("");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin hóa đơn"));

        jPanel12.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Số hóa đơn:");

        jTextField2.setEditable(false);

        jLabel3.setText("Ngày tạo hóa đơn:");

        jLabel4.setText("Nhân viên bán hàng:");

        cbbNhanVien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel16.setText("Ghi chú");

        jdcNgayTaoHD.setDate(new java.util.Date(System.currentTimeMillis()));
        jdcNgayTaoHD.setDateFormatString("dd/MM/yyyy");
        jdcNgayTaoHD.setLocale(new java.util.Locale("vi","VN"));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtGhiChu)
                    .addComponent(cbbNhanVien, 0, 220, Short.MAX_VALUE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jdcNgayTaoHD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jdcNgayTaoHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbbNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setText("Tên/Mã khách hàng:");

        txtKhungTKKH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtKhungTKKHKeyReleased(evt);
            }
        });

        jButton8.setText("Tìm kiếm");

        jLabel6.setText("Tên KH");

        jLabel7.setText("Giới tính");

        jLabel8.setText("Số ĐT");

        jLabel9.setText("Ngày sinh");

        jLabel10.setText("Địa chỉ");

        jLabel11.setText("Ghi chú");

        cbbGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nữ", "Nam" }));

        datNgaySinh.setDateFormatString("dd/MM/yyyy");
        datNgaySinh.setLocale(new java.util.Locale("vi","vn"));

        jLabel12.setText("Mã KH");

        txtMaKH.setEditable(false);

        chbTaoKHMoi.setSelected(true);
        chbTaoKHMoi.setText("Tạo KH mới");
        chbTaoKHMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbTaoKHMoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txtKhungTKKH, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtGhiChuKH)
                            .addComponent(txtDiaChi)
                            .addComponent(txtSoDT)
                            .addComponent(txtTenKH)
                            .addComponent(cbbGioiTinh, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(datNgaySinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtMaKH))
                        .addGap(18, 18, 18)
                        .addComponent(chbTaoKHMoi)
                        .addGap(36, 36, 36)))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtKhungTKKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtSoDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel9))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(datNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtGhiChuKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chbTaoKHMoi))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        btnThanhToan.setText("Thanh toán");
        btnThanhToan.setToolTipText("");
        btnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanActionPerformed(evt);
            }
        });

        btnTaoHDMoi.setText("Tạo hóa đơn mới");
        btnTaoHDMoi.setToolTipText("");
        btnTaoHDMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoHDMoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtKhungTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnTaoHDMoi)
                        .addGap(18, 18, 18)
                        .addComponent(btnThanhToan)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtKhungTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThanhToan)
                    .addComponent(btnTaoHDMoi))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanActionPerformed
        //Kiểm tra blank
        if (tblGioHang.getRowCount() == 0) {
            XuLyThongBao.hienThiThongBao(new ThongBao("Chưa thêm sản phẩm nào vào giỏ hàng!", ThongBao.LOI));
            return;
        }
        if (txtMaKH.getText().isEmpty() && !chbTaoKHMoi.isSelected()) {
            XuLyThongBao.hienThiThongBao(new ThongBao("Chưa chọn khách hàng!", ThongBao.LOI));
            return;
        }
        if (chbTaoKHMoi.isSelected()) {
            DTO.DTOKhachHang kh = new DTO.DTOKhachHang(
                    txtTenKH.getText(),
                    cbbGioiTinh.getSelectedIndex(),
                    txtSoDT.getText(),
                    ConvertDateFormat.chuyenNgay(datNgaySinh.getDate()),
                    txtDiaChi.getText(),
                    txtGhiChu.getText());
            BLL.BLLKhachHang.them(kh);
            loadDuLieuVaoForm(DALKhachHang.layKHVuaThem().getMaKH());
        }
        CustomObjectItem selectedItem = (CustomObjectItem) cbbNhanVien.getSelectedItem();
        int maNV = selectedItem.layMa();
        int soDong = tblGioHang.getRowCount();
        int[][] dsSanPham = new int[soDong][2];
        for (int i = 0; i < soDong; i++) {
            dsSanPham[i][0] = Integer.parseInt(tblGioHang.getValueAt(i, 0).toString());
            dsSanPham[i][1] = Integer.parseInt(tblGioHang.getValueAt(i, 2).toString());
        }
        XuLyThongBao.hienThiThongBao(DAL.DALHoaDon.taoHoaDonTransaction(
                Integer.parseInt(txtMaKH.getText()),
                maNV,
                ConvertDateFormat.chuyenNgay(jdcNgayTaoHD.getDate()),
                txtGhiChu.getText(),
                dsSanPham,
                Integer.parseInt(txtTongTien.getText())));
    }//GEN-LAST:event_btnThanhToanActionPerformed

    private void btnTaoHDMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoHDMoiActionPerformed
        //Xóa và khởi tạo lại tất cả component
        this.removeAll();
        initComponents();
        XuLyCbb.capNhatCbb(cbbNhanVien, DAL.DALNhanVien.layDuLieu());
    }//GEN-LAST:event_btnTaoHDMoiActionPerformed

    private void txtKhungTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKhungTimKiemKeyReleased
        //Chừa lại phím lên xuống để lựa chọn item
        if (evt.getKeyCode() == evt.VK_UP || evt.getKeyCode() == evt.VK_DOWN) {
            popMenuTimKiem.requestFocus();
            return;
        }
        String keyWord = txtKhungTimKiem.getText();
        DTOSanPham arrItem[] = DALSanPham.searchBy(keyWord);
        popMenuTimKiem.removeAll();
        popMenuTimKiem.setVisible(false);
        for (DTOSanPham item : arrItem) {
            CustomMenuItem menuItem = new CustomMenuItem(item.getiDSanPham(), item.getTenSP());
            //Thêm sự kiện cho menuItem: khi click vào item -> đổ thông tin sản phẩm tương ứng lên form
            menuItem.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(ActionEvent e) {
                    txtKhungTimKiem.setText("");
                    hienDlgSoLuong(item.getiDSanPham());
                }
            });
            popMenuTimKiem.add(menuItem);
        }
        popMenuTimKiem.show(txtKhungTimKiem, 0, txtKhungTimKiem.getHeight());
        txtKhungTimKiem.requestFocus();
    }//GEN-LAST:event_txtKhungTimKiemKeyReleased

    private void themVaoGioHang(int idSanPham, int soLuong) {
        if (soLuong == 0) {
            return;
        }
        DefaultTableModel tblModel = (DefaultTableModel) tblGioHang.getModel();
        DTOSanPham sp = DALSanPham.layDuLieu(idSanPham);
        Object[] item = new Object[6];
        item[0] = sp.getiDSanPham();
        item[1] = sp.getTenSP();
        item[2] = soLuong;
        item[3] = sp.getDonViTinh();
        item[4] = sp.getGiaBan();
        int thanhTien = sp.getGiaBan() * soLuong;
        item[5] = thanhTien;
        tblModel.addRow(item);
        capNhatTongTien("+", thanhTien);
    }

    private void hienDlgSoLuong(int idSanPham) {
        DlgNhapSoLuong dlg = new DlgNhapSoLuong(new Frame(), true, idSanPham);
        dlg.setVisible(true);
        themVaoGioHang(idSanPham, dlg.getSoLuong());
    }

    private void capNhatTongTien(String ope, int giaTri) {
        int tongTien = Integer.parseInt(txtTongTien.getText());
        switch (ope) {
            case "+":
                txtTongTien.setText(Integer.toString(tongTien + giaTri));
                break;
            case "-":
                txtTongTien.setText(Integer.toString(tongTien - giaTri));
                break;
        }
        txtTongTien.requestFocus();
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtTienKhachTraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTienKhachTraKeyReleased
        tinhVaHienThiTienDu();
    }//GEN-LAST:event_txtTienKhachTraKeyReleased

    private void txtTongTienFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTongTienFocusGained
        tinhVaHienThiTienDu();
    }//GEN-LAST:event_txtTongTienFocusGained

    private void txtKhungTKKHKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKhungTKKHKeyReleased
        //Chừa lại phím lên xuống để lựa chọn item
        if (evt.getKeyCode() == evt.VK_UP || evt.getKeyCode() == evt.VK_DOWN) {
            popMenuTKKH.requestFocus();
            return;
        }
        String keyWord = txtKhungTKKH.getText();
        DTOKhachHang arrItem[] = DALKhachHang.searchBy(keyWord);
        popMenuTKKH.removeAll();
        popMenuTKKH.setVisible(false);
        for (DTOKhachHang item : arrItem) {
            CustomMenuItem menuItem = new CustomMenuItem(item.getMaKH(), item.getTenKH());
            //Thêm sự kiện cho menuItem: khi click vào item -> đổ thông tin sản phẩm tương ứng lên form
            menuItem.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(ActionEvent e) {
                    txtKhungTKKH.setText("");
                    loadDuLieuVaoForm(menuItem.getMa());
                    chbTaoKHMoi.setSelected(false);
                }
            });
            popMenuTKKH.add(menuItem);
        }
        popMenuTKKH.show(txtKhungTKKH, 0, txtKhungTKKH.getHeight());
        txtKhungTKKH.requestFocus();
    }//GEN-LAST:event_txtKhungTKKHKeyReleased

    private void chbTaoKHMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbTaoKHMoiActionPerformed
        if(chbTaoKHMoi.isSelected()){
            txtMaKH.setText("");
        }
    }//GEN-LAST:event_chbTaoKHMoiActionPerformed

    private void loadDuLieuVaoForm(int maKH) {
        DTOKhachHang ttkh = DALKhachHang.layDuLieu(maKH);
        txtMaKH.setText(Integer.toString(ttkh.getMaKH()));
        txtTenKH.setText(ttkh.getTenKH());
        cbbGioiTinh.setSelectedIndex(ttkh.getGioiTinh());
        txtSoDT.setText(ttkh.getSoDT());
        datNgaySinh.setDate(ConvertDateFormat.chuyenNgay(ttkh.getNgaySinh()));
        txtDiaChi.setText(ttkh.getDiaChi());
        txtGhiChu.setText(ttkh.getGhiChu());
    }

    private void tinhVaHienThiTienDu() {
        if (txtTienKhachTra.getText().equals("")) {
            return;
        }
        int tienDu = Integer.parseInt(txtTienKhachTra.getText()) - Integer.parseInt(txtTongTien.getText());
        if (tienDu < 0) {
            txtTienDu.setForeground(java.awt.Color.RED);
        } else {
            txtTienDu.setForeground(java.awt.Color.BLUE);
        }
        txtTienDu.setText(Integer.toString(tienDu));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblTienDu;
    private javax.swing.JLabel LblTienKhachTra;
    private javax.swing.JLabel LblTongTien;
    private javax.swing.JPanel PnlTongTienHD;
    private javax.swing.JButton btnTaoHDMoi;
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JComboBox<String> cbbGioiTinh;
    private javax.swing.JComboBox<String> cbbNhanVien;
    private javax.swing.JCheckBox chbTaoKHMoi;
    private com.toedter.calendar.JDateChooser datNgaySinh;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField2;
    private com.toedter.calendar.JDateChooser jdcNgayTaoHD;
    private javax.swing.JPopupMenu popMenuTKKH;
    private javax.swing.JPopupMenu popMenuTimKiem;
    private javax.swing.JTable tblGioHang;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtGhiChu;
    private javax.swing.JTextField txtGhiChuKH;
    private javax.swing.JTextField txtKhungTKKH;
    private javax.swing.JTextField txtKhungTimKiem;
    private javax.swing.JTextField txtMaKH;
    private javax.swing.JTextField txtSoDT;
    private javax.swing.JTextField txtTenKH;
    private javax.swing.JTextField txtTienDu;
    private javax.swing.JTextField txtTienKhachTra;
    private javax.swing.JTextField txtTongTien;
    // End of variables declaration//GEN-END:variables
}
